// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: money.proto

package com.google.type;

public final class MoneyProto {
  private MoneyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_type_Money_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_type_Money_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013money.proto\022\013google.type\"<\n\005Money\022\025\n\rc" +
      "urrency_code\030\001 \001(\t\022\r\n\005units\030\002 \001(\003\022\r\n\005nan" +
      "os\030\003 \001(\005B`\n\017com.google.typeB\nMoneyProtoP" +
      "\001Z6google.golang.org/genproto/googleapis" +
      "/type/money;money\370\001\001\242\002\003GTPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_type_Money_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_type_Money_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_type_Money_descriptor,
        new String[] { "CurrencyCode", "Units", "Nanos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
