// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package Test.opensource.protobuf.customizedatatype.pojo;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_danielpadua_protobufexample_contracts_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_danielpadua_protobufexample_contracts_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023CustomerProto.proto\022%danielpadua.proto" +
      "bufexample.contracts\032\037google/protobuf/ti" +
      "mestamp.proto\032\013money.proto\032\ndate.proto\"\334" +
      "\001\n\010Customer\022\n\n\002id\030\001 \001(\003\022\r\n\005photo\030\002 \001(\014\022\014" +
      "\n\004name\030\003 \001(\t\022$\n\tbirthdate\030\004 \001(\0132\021.google" +
      ".type.Date\022#\n\007balance\030\005 \001(\0132\022.google.typ" +
      "e.Money\022-\n\tcreatedAt\030\006 \001(\0132\032.google.prot" +
      "obuf.Timestamp\022-\n\tupdatedAt\030\007 \001(\0132\032.goog" +
      "le.protobuf.TimestampBn\n-dev.danielpadua" +
      ".protobufexamplejava.contractsB\rCustomer" +
      "ProtoP\001\252\002+DanielPadua.ProtobufExampleDot" +
      "net.Contractsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.MoneyProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
        });
    internal_static_danielpadua_protobufexample_contracts_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_danielpadua_protobufexample_contracts_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_danielpadua_protobufexample_contracts_Customer_descriptor,
        new String[] { "Id", "Photo", "Name", "Birthdate", "Balance", "CreatedAt", "UpdatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.MoneyProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
