// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomerProto.proto

package Test.opensource.protobuf.customizedatatype.pojo;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:danielpadua.protobufexample.contracts.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>bytes photo = 2;</code>
   * @return The photo.
   */
  com.google.protobuf.ByteString getPhoto();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.google.type.Date birthdate = 4;</code>
   * @return Whether the birthdate field is set.
   */
  boolean hasBirthdate();
  /**
   * <code>.google.type.Date birthdate = 4;</code>
   * @return The birthdate.
   */
  com.google.type.Date getBirthdate();
  /**
   * <code>.google.type.Date birthdate = 4;</code>
   */
  com.google.type.DateOrBuilder getBirthdateOrBuilder();

  /**
   * <code>.google.type.Money balance = 5;</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <code>.google.type.Money balance = 5;</code>
   * @return The balance.
   */
  com.google.type.Money getBalance();
  /**
   * <code>.google.type.Money balance = 5;</code>
   */
  com.google.type.MoneyOrBuilder getBalanceOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
